#!/bin/bash

CGBPF_FILTER=$1
CGBPF_FILTER_LEN=${#CGBPF_FILTER}
CGBPF_OUT=$2

echo "CGBPF: bpftrace -q $CGBPF_START_BT $CGBPF_FILTER $CGBPF_FILTER_LEN > $CGBPF_OUT"

bpftrace -q "$CGBPF_START_BT" "$CGBPF_FILTER" "$CGBPF_FILTER_LEN" > "$CGBPF_OUT"
chmod 777 "$CGBPF_OUT"
